---
title: "Data Dictionary"
output: html_notebook
---

This notebook is for making up a data dictionary.

```{r}
rm(list=ls())
```

```{r}
library(readr)
library(kableExtra)
library(zoo)
library(psych)
```

```{r}
annual_plant_level_data <- read_csv("data/Cleaned Data/eGRID_ercot.csv")
daily_fuel_mix_report <- read_csv("data/Cleaned Data/fuel_mix_report_clean_wide.csv")
daily_fuel_mix_report[is.na(daily_fuel_mix_report)] <- 0
hourly_spot_prices_DAM <- read_csv("data/Cleaned Data/spot_prices_DAM.csv")
annual_wind_turbine_data <- read_csv("data/Cleaned Data/txwtdb.csv")

```
```{r}
#hourly_zonal_spot_price_DAM <- hourly_spot_prices_DAM[hourly_spot_prices_DAM$`Settlement Point` == "HB_HUBAVG",]

#hourly_hubavg_spot_price_DAM$date_time <- paste(hourly_hubavg_spot_price_DAM$`Delivery Date`, hourly_hubavg_spot_price_DAM$`Hour Ending`)
```

```{r}
#kable(head(annual_plant_level_data, 10), format = "html", caption = "Portion of dataset")
```

Going to use the zoo package to make these time series a little easier to work with...


```{r}
#this is now done in price_cleaning.rmd

#stat <- function(x) c(min_spot_price = min(x), max_spot_price = max(x), mean_spot_price = mean(x))

#spot_price_zoo <- read.zoo(file = "data/Cleaned Data/hourly_zonal_spot_price_DAM.csv", header = TRUE, sep = ",", format = "%Y-%m-%d", aggregate = stat)
```


```{r}

fuel_mix_zoo <- read.zoo(file="data/Cleaned Data/fuel_mix_report_15min_wide.csv", header = TRUE, sep=",", format = "%Y-%m-%d %T")

fuel_mix_zoo <- fuel_mix_zoo[,! colnames(fuel_mix_zoo) %in% c("Season")]

x <- read.csv(file="data/Cleaned Data/fuel_mix_report_15min_wide.csv")
x <- na.fill(x,0)
fuel_mix_zoo <- zoo(x)

```


```{r}

plant_level_zoo <- read.zoo(file="data/Cleaned Data/eGRID_wide_aggregate.csv", header = TRUE, sep=",", format = "%Y")

```


```{r}
zonal_spot_price_zoo <- read.zoo(file = "data/Cleaned Data/daily_dam_zonal_spot_price_agg.csv", header = TRUE, sep=",", format = "%Y-%m-%d")

zonal_spot_price_zoo <- zonal_spot_price_zoo[,! colnames(zonal_spot_price_zoo) %in% c("min_spot_price","max_spot_price")]

```

```{r}
#turbine_zoo <- read.zoo(file="data/Cleaned Data/txwtdb.csv", header = TRUE, sep=",", format = "%Y")
```


```{r}
#annual_wind_turbine_data <-  annual_wind_turbine_data[!is.na(annual_wind_turbine_data$p_year),]

#turbine_zoo <- read.zoo(annual_wind_turbine_data, format="%Y")
```

```{r}
dates <- seq(from = min(index(fuel_mix_zoo)), to = max(index(fuel_mix_zoo)), by = 1)
empty <- zoo(, dates)

filled.fuel_mix_zoo <- merge(fuel_mix_zoo, empty, all = TRUE)

filled.fuel_mix_zoo <- na.locf(merge(fuel_mix_zoo, empty, all = TRUE))

dates <- seq(from = min(index(zonal_spot_price_zoo)), to = max(index(zonal_spot_price_zoo)), by = 1)
empty <- zoo(, dates)

filled.spot_price_zoo <- merge(zonal_spot_price_zoo, empty, all = TRUE)

filled.spot_price_zoo <- na.locf(merge(zonal_spot_price_zoo, empty, all = TRUE))
```

```{r}
#naive_daily_merge <- merge(fuel_mix_zoo, spot_price_zoo, all=TRUE)

filled_daily_merge <- merge(filled.fuel_mix_zoo, filled.spot_price_zoo, all=TRUE)

#write.zoo(naive_merge, file="data/Cleaned Data/cleaned_timeseries_data_naive.csv", index.name = "Date", sep=",")

#naive_merge <- read.zoo(file="data/Cleaned Data/cleaned_timeseries_data_naive.csv", header = TRUE, sep=",", format = "%Y-%m-%d")

# all but b
#filled_daily_merge <- filled_daily_merge[, colnames(filled_daily_merge) != "Season"]


describe(filled_daily_merge)

#splined_merge <- na.spline(naive_daily_merge)

merge_fill0 <- na.fill(filled_daily_merge,0)

```

```{r}
dates <- seq(from = as.Date("2010-12-01"), to = as.Date("2019-12-31"), by = 1)
empty <- zoo(, dates)

trimmed_zeroes <- merge(empty, merge_fill0, all=FALSE)


# removing the max and min spot prices 
colnames(trimmed_zeroes)[10] = 'mean_spot_price'
```

```{r}
write.zoo(merge_fill0, file="data/Cleaned Data/cleaned_timeseries_data_zeroes.csv", index.name = "Date", sep=",")

write.zoo(trimmed_zeroes, file="data/Cleaned Data/cleaned_timeseries_data_zeroes_trimmed.csv", index.name = "Date", sep=",")

#write.zoo(splined_merge, file="data/Cleaned Data/cleaned_timeseries_data_splined.csv", index.name = "Date", sep=",")

#write.zoo(filled_daily_merge, file="data/Cleaned Data/cleaned_timeseries_data_filled.csv", index.name = "Date", sep=",")
```


```{r}
#autoplot.zoo(filled_daily_merge)
```

```{r}
describe(merge_fill0)

describe(trimmed_zeroes)
```


```{r}
library(ggplot2)
library(GGally)

#ggpairs(merge_fill0)    
```

```{r}
cleaned_timeseries_data_zeroes <- read_csv("~/EER Thesis/ERCOT Transition Analysis/data/Cleaned Data/cleaned_timeseries_data_zeroes.csv", 
    col_types = cols(Date = col_date(format = "%Y-%m-%d")))

trimmed_timeseries_data_zeroes <- read_csv("~/EER Thesis/ERCOT Transition Analysis/data/Cleaned Data/cleaned_timeseries_data_zeroes_trimmed.csv", 
    col_types = cols(Date = col_date(format = "%Y-%m-%d")))
```

```{r}
#ggpairs(cleaned_timeseries_data_zeroes,lower = list(continuous = "smooth"))

#cbPalette <- c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "#999999", "#000000")


#ggpairs(cleaned_timeseries_data_zeroes, mapping=ggplot2::aes(colour = as.factor(Season), alpha=0.75),
#              lower=list(continuous="smooth"),
#              #upper=list(continuous="blank"),
#              axisLabels="none", switch="both") +
#              theme_bw() +
#              scale_color_manual(values=cbPalette) +
#              scale_fill_manual(values=cbPalette)

#ggsave("daily_correlogram.png", path="misc_stuff/", device="png",width=14, height=14)
```

```{r}
#ggcorr(cleaned_timeseries_data_zeroes)

ggcorr(trimmed_timeseries_data_zeroes)

ggsave("daily_correlation_matrix.png", path="misc_stuff/", device = "png")

```

```{r}
library(forecast)
Ccf(cleaned_timeseries_data_zeroes[,3], cleaned_timeseries_data_zeroes[,4])
acf(cleaned_timeseries_data_zeroes, main = "Significant Autocorrelations")
```

```{r}
coal_arima <- auto.arima(trimmed_timeseries_data_zeroes[,3])


checkresiduals(coal_arima, main="Coal Residuals")

wind_arima <- auto.arima(trimmed_timeseries_data_zeroes[,4])


checkresiduals(wind_arima, main="Wind Residuals")

gas_arima <- auto.arima(trimmed_timeseries_data_zeroes[,2])


checkresiduals(gas_arima, main="Gas Residuals")
```


Let's make the data tall/long for some nice graphing.
```{r}
library(tidyr)

long_cleaned_data <- gather(cleaned_timeseries_data_zeroes, Date, "MWh", Gas:Gas_Price)
```


```{r}
```

```{r}
plot(merge_fill0,col=rainbow(ncol(merge_fill0))) 


plot(trimmed_zeroes[,colnames(trimmed_zeroes) != "Season"],col=rainbow(ncol(trimmed_zeroes[,colnames(trimmed_zeroes) != "Season"])), main="Daily Timeseries Data") 

```

