---
title: "ERCOT Quantic Regression"
output:
  html_document:
    df_print: paged
---



```{r}
library(quantreg)
library(readr)
library(GGally)
library(broom)
library(stargazer)
```

```{r}
rm(list=ls())
```


The following adapted from the R Notebook "Tutorial: Quantile Regression using R" by Ibn Abdullah, February 15, 2016
https://rstudio-pubs-static.s3.amazonaws.com/152505_49d1881e3fe64f0bad072282c36a6ca5.html

```{r}
ERCOTData <- read.csv("data/ERCOT_Dataset_8June2021.csv", na.strings = ".")
```

```{r}
stargazer(ERCOTData[ ,10:89], type="text")
```

```{r}
datatable=data.frame(rtm_price = ERCOTData$RTM_price_weighted_Hub, 
                     wind_gen = ERCOTData$wind, 
                     gas_price = ERCOTData$henry, 
                     sys_load = ERCOTData$mwh_sys, 
                     nuclear_gen = ERCOTData$nuclear, 
                     solar_gen = ERCOTData$solar)

datatable <- na.omit(datatable)

cor(datatable)
```

```{r}
#ggpairs(datatable)

# ggpairs(datatable, alpha=0.2,
#               lower=list(continuous="smooth", color = "red"),
#               #upper=list(continuous="blank"),
#               axisLabels="none", switch="both") +
#               theme_bw()

```

```{r}
Y = cbind(rtm_price = datatable$rtm_price)
X = cbind(wind_gen = datatable$wind_gen, gas_price = datatable$gas_price, sys_load = datatable$sys_load, nuclear_gen = datatable$nuclear_gen, solar_gen = datatable$solar_gen)

```

```{r}
hist(Y, prob=TRUE, col = "blue", border = "black", main = "Real Time Price Histogram")
lines(density(na.omit(Y)))

```

```{r}
OLSreg=lm(Y~X)

summary(OLSreg)
```

```{r}
Qreg25=rq(Y~X, tau=0.25)

summary(Qreg25)
```

```{r}
Qreg75=rq(Y~X, tau=0.75)

summary(Qreg75)
```

```{r}
anova(Qreg25, Qreg75)
```

```{r}
#QR=rq(Y~X, tau=c(0.5, 0.75, 0.85, 0.95))

#sumQR=summary(QR, se="boot")
```

```{r}
#plot(sumQR)
```



```{r}
#TODO specify one or more regions rather than just one...
regional_and_time_regressions <- function(df, time=11, region='ercot', t=c(0.10, 0.25, 0.50, 0.75, 0.90)){
  #'''default time 11 AM, default region is system wide, default quantiles are 0.10, 0.25, 0.50, 0.75, 0.90'''
  attach(df)
  newdata <- df[ which(hourstart==time),]
  detach(df)
  
  attach(newdata)
  
  if (region=='ercot'){
    #datatable = data.frame(RTM_price_weighted_Hub, wind, henry, mwh_sys, nuclear, solar)
    Y = cbind(RTM_price_weighted_Hub)
    X = cbind(wind, henry, mwh_sys, nuclear, solar)
  } else if (region=='north') {
    #datatable = data.frame(RTM_price_weighted_north, wind_actual_west_north, henry, NorthLoad, nuclear, solar)
    Y = cbind(RTM_price_weighted_north)
    X = cbind(wind_actual_west_north, "rest_of_system_wind" = wind - wind_actual_west_north, henry, NorthLoad, "rest_of_system_load" = mwh_sys - NorthLoad, nuclear, solar)
  } else if (region=='houston') {
    #datatable = data.frame(RTM_price_weighted_houston, wind_actual_south_houston, henry, HouLoad, nuclear, solar)
    Y = cbind(RTM_price_weighted_houston)
    X = cbind(wind_actual_south_houston, "rest_of_system_wind" = wind - wind_actual_south_houston, henry, HouLoad, "rest_of_system_load" = mwh_sys - HouLoad, nuclear, solar)
  } else if (region=='south') {
    #datatable = data.frame(RTM_price_weighted_south, wind_actual_south_houston, henry, SOUTHLoad, nuclear, solar)
    Y = cbind(RTM_price_weighted_south)
    X = cbind(wind_actual_south_houston, "rest_of_system_wind" = wind - wind_actual_south_houston, henry, SOUTHLoad, "rest_of_system_load" = mwh_sys - SOUTHLoad, nuclear, solar)
  } else if (region=='west') {
    #datatable = data.frame(RTM_price_weighted_west, wind_actual_west_north, henry, WestLoad, nuclear, solar)
    Y = cbind(RTM_price_weighted_west)
    X = cbind(wind_actual_west_north, "rest_of_system_wind" = wind - wind_actual_west_north, henry, WestLoad, "rest_of_system_load" = mwh_sys - WestLoad, nuclear, solar)
  } else {
    print("give better region name pls")
    break
  }

  detach(newdata)

  QR=rq(Y~X, tau=t)

  sumQR=summary(QR, se="boot")
  
  return(sumQR)

  
  
}

```

```{r}


for (r in c('ercot', 'north', 'west', 'south', 'houston')){
  for (t in c(4,16)) {
    #print(paste("Quantile Regression for the ",r,"zone at ",t," o'clock."))
    png(filename = paste("misc_stuff\\graphing_files\\Quantile_Results\\15-19_quantile_", r, "_", t, ".png",sep = ""))
    par(oma=c(3,3,3,3))
    plot(regional_and_time_regressions(ERCOTData[ERCOTData$year>=2015 & ERCOTData$year<=2019,],region = r, time = t))
    mtext(paste("Quantile Regression for the ",r,"zone at ",t," o'clock. 2015-2019 data"), outer = TRUE, cex = 1.5, line = 1)
    dev.off()
  }
}

```

```{r}
plot(sumQR)
```





Next, the example quantreg code from https://rdrr.io/cran/quantreg/man/rq.html



```{r}
# data(stackloss)
# rq(stack.loss ~ stack.x,.5)  #median (l1) regression  fit for the stackloss data. 
# rq(stack.loss ~ stack.x,.25)  #the 1st quartile, 
#       #note that 8 of the 21 points lie exactly on this plane in 4-space! 
# rq(stack.loss ~ stack.x, tau=-1)   #this returns the full rq process
# rq(rnorm(50) ~ 1, ci=FALSE)    #ordinary sample median --no rank inversion ci
# rq(rnorm(50) ~ 1, weights=runif(50),ci=FALSE)  #weighted sample median 


rq(Y ~ X,.5)  #median (l1) regression  fit for the stackloss data. 
rq(Y ~ X,.25)  #the 1st quartile, 
        #note that 8 of the 21 points lie exactly on this plane in 4-space! 
#rq(Y ~ X, tau=-1)   #this returns the full rq process, vector size of 171 GB too big for my machine qq
rq(rnorm(50) ~ 1, ci=FALSE)    #ordinary sample median --no rank inversion ci
rq(rnorm(50) ~ 1, weights=runif(50),ci=FALSE)  #weighted sample median 

```

```{r}
#plot of engel data and some rq lines see KB(1982) for references to data
# data(engel)
# attach(engel)
# plot(income,foodexp,xlab="Household Income",ylab="Food Expenditure",type = "n", cex=.5)
# points(income,foodexp,cex=.5,col="blue")
# taus <- c(.05,.1,.25,.75,.9,.95)
# xx <- seq(min(income),max(income),100)
# f <- coef(rq((foodexp)~(income),tau=taus))
# yy <- cbind(1,xx)%*%f
# for(i in 1:length(taus)){
#         lines(xx,yy[,i],col = "gray")
#         }
# abline(lm(foodexp ~ income),col="red",lty = 2)
# abline(rq(foodexp ~ income), col="blue")
# legend(3000,500,c("mean (LSE) fit", "median (LAE) fit"),
# 	col = c("red","blue"),lty = c(2,1))


plot(log(wind),log(RTM_price_weighted_Hub),xlab="Wind Generation (MWh)",ylab="RTM Price (Weighted Hub Average, $/MWh)",type = "n", cex=.5)
points(wind,RTM_price_weighted_Hub,cex=.5,col="blue")
taus <- c(.05,.1,.25,.75,.9,.95)
xx <- seq(min(na.omit(wind)),max(na.omit(wind)),100)
f <- coef(rq((RTM_price_weighted_Hub)~(wind),tau=taus))
yy <- cbind(1,xx)%*%f
for(i in 1:length(taus)){
        lines(xx,yy[,i],col = "gray")
        }
abline(lm(log(RTM_price_weighted_Hub) ~ log(wind)),col="red",lty = 2)
abline(rq(RTM_price_weighted_Hub ~ wind), col="blue")
legend(3000,500,c("mean (LSE) fit", "median (LAE) fit"),
	col = c("red","blue"),lty = c(2,1))
```

```{r}
#Example of plotting of coefficients and their confidence bands
#plot(summary(rq(foodexp~income,tau = 1:49/50,data=engel)))

#this takes forever, I ran it once and exported the figure...
#plot(summary(rq(RTM_price_weighted_Hub~wind,tau = 1:49/50,data=ERCOTData)))
```

```{r}
#Example to illustrate inequality constrained fitting
n <- 100
p <- 5
X <- matrix(rnorm(n*p),n,p)
y <- .95*apply(X,1,sum)+rnorm(n)
#constrain slope coefficients to lie between zero and one
R <- cbind(0,rbind(diag(p),-diag(p)))
r <- c(rep(0,p),-rep(1,p))
rq(y~X,R=R,r=r,method="fnc")
```

```{r}
library(plotly)
library(MASS)
library(dplyr)

p <- ggplot(datatable, aes(log(wind), log(RTM_price_weighted_Hub))) +
  geom_point(size = 1) +
  geom_quantile(quantiles = 1:4/5, size = 1, aes(colour = ..quantile..)) +
  scale_alpha(range = c(0.3, 0.7)) +
  geom_smooth(method=lm , color="red", fill="#69b3a2", se=TRUE)

p
```

```{r}

attach(ERCOTData[ERCOTData$hourstart==18,])
```

```{r}
west_6pm_datatable=data.frame(RTM_price_weighted_west, wind_actual_west_north, henry, WestLoad, nuclear, solar)

west_6pm_datatable <- na.omit(west_6pm_datatable)


p <- ggplot(west_6pm_datatable, aes(log(wind_actual_west_north), log(RTM_price_weighted_west))) +
  geom_point(size = 1) +
  geom_quantile(quantiles = 1:19/20, size = 2, aes(colour = ..quantile..)) +
  scale_alpha(range = c(0.3, 0.7)) +
  geom_smooth(method=lm , color="red", fill="#69b3a2", se=TRUE)

p
```

```{r}
detach(ERCOTData[ERCOTData$hourstart==18,])
```

```{r}
library(jtools)
```

```{r}
Y = cbind(rtm_price = datatable$rtm_price)
X = cbind(wind_gen = datatable$wind_gen, gas_price = datatable$gas_price, sys_load = datatable$sys_load, nuclear_gen = datatable$nuclear_gen, solar_gen = datatable$solar_gen)
```

```{r}
OLSreg=lm(Y~X)
Qreg=rq(Y~X, tau = c(1))
```

```{r}
summ(OLSreg)
summ(Qreg, se = "boot")
```

Now I'm going to replicate and expand on the results from Rudolph et al. (2021)

I'll start by whipping up some dataframes...

```{r}

north_zone_df <- data.frame(cbind(price = log(ERCOTData$RTM_price_weighted_north), year = ERCOTData$year, month = ERCOTData$month, day = ERCOTData$day, hour = ERCOTData$hourstart, nuclear = log(ERCOTData$nuclear), wind = log(ERCOTData$wind), solar = log(ERCOTData$solar), gas_price = log(ERCOTData$henry), local_load = log(ERCOTData$NorthLoad), rest_of_system_load = log((ERCOTData$mwh_sys - ERCOTData$NorthLoad))))

houston_zone_df <- data.frame(cbind(price = log(ERCOTData$RTM_price_weighted_houston), year = ERCOTData$year, month = ERCOTData$month, day = ERCOTData$day, hour = ERCOTData$hourstart, nuclear= log(ERCOTData$nuclear), wind = log(ERCOTData$wind), solar = log(ERCOTData$solar), gas_price = log(ERCOTData$henry), local_load = log(ERCOTData$HouLoad), rest_of_system_load = log((ERCOTData$mwh_sys - ERCOTData$HouLoad))))

west_zone_df <- data.frame(cbind(price = log(ERCOTData$RTM_price_weighted_west), year = ERCOTData$year, month = ERCOTData$month, day = ERCOTData$day, hour = ERCOTData$hourstart, nuclear = log(ERCOTData$nuclear), wind = log(ERCOTData$wind), solar = log(ERCOTData$solar), gas_price = log(ERCOTData$henry), local_load = log(ERCOTData$WestLoad), rest_of_system_load = log((ERCOTData$mwh_sys - ERCOTData$WestLoad))))


north_zone_df[sapply(north_zone_df, simplify = 'matrix', is.infinite)] <- 0
west_zone_df[sapply(west_zone_df, simplify = 'matrix', is.infinite)] <- 0
houston_zone_df[sapply(houston_zone_df, simplify = 'matrix', is.infinite)] <- 0

```

Now that we have our data, let's make some models.

```{r}

annual_north_qrs <- lapply(split(north_zone_df,north_zone_df$year), 
                           function(x) rq(x$price ~ ., 
                                          data = x[ ,6:11], 
                                          tau = c(.1, .25, .5, .75, .9)))

annual_houston_qrs <- lapply(split(houston_zone_df,houston_zone_df$year), 
                           function(x) rq(x$price ~ ., 
                                          data = x[ ,6:11], 
                                          tau = c(.1, .25, .5, .75, .9)))

annual_west_qrs <- lapply(split(west_zone_df,west_zone_df$year), 
                           function(x) rq(x$price ~ ., 
                                          data = x[ ,6:11], 
                                          tau = c(.1, .25, .5, .75, .9)))


monthly_north_qrs <- lapply(split(north_zone_df,north_zone_df$month), 
                           function(x) rq(x$price ~ ., 
                                          data = x[ ,6:11], 
                                          tau = c(.1, .25, .5, .75, .9)))

monthly_houston_qrs <- lapply(split(houston_zone_df,houston_zone_df$month), 
                           function(x) rq(x$price ~ ., 
                                          data = x[ ,6:11], 
                                          tau = c(.1, .25, .5, .75, .9)))

monthly_west_qrs <- lapply(split(west_zone_df,west_zone_df$month), 
                           function(x) rq(x$price ~ ., 
                                          data = x[ ,6:11], 
                                          tau = c(.1, .25, .5, .75, .9)))

hourly_north_qrs <- lapply(split(north_zone_df,north_zone_df$hour), 
                           function(x) rq(x$price ~ ., 
                                          data = x[ ,6:11], 
                                          tau = c(.1, .25, .5, .75, .9)))

hourly_houston_qrs <- lapply(split(houston_zone_df,houston_zone_df$hour), 
                           function(x) rq(x$price ~ ., 
                                          data = x[ ,6:11], 
                                          tau = c(.1, .25, .5, .75, .9)))

hourly_west_qrs <- lapply(split(west_zone_df,west_zone_df$hour), 
                           function(x) rq(x$price ~ ., 
                                          data = x[ ,6:11], 
                                          tau = c(.1, .25, .5, .75, .9)))


```

Annual Summaries

```{r}
for (i in names(annual_north_qrs)) {
    modeli <- annual_north_qrs[[i]]
    tidy_qr <- tidy(modeli)
    write.csv(tidy_qr, 
              file = paste("~/EER Thesis/ERCOT Transition Analysis/misc_stuff/regression_results/",
                            "annual_north_quantreg_", i, ".csv", sep = ""))
}

for (i in names(annual_houston_qrs)) {
    modeli <- annual_houston_qrs[[i]]
    tidy_qr <- tidy(modeli)
    write.csv(tidy_qr, 
              file = paste("~/EER Thesis/ERCOT Transition Analysis/misc_stuff/regression_results/",
                            "annual_houston_quantreg_", i, ".csv", sep = ""))
}

for (i in names(annual_west_qrs)) {
    modeli <- annual_west_qrs[[i]]
    tidy_qr <- tidy(modeli)
    write.csv(tidy_qr, 
              file = paste("~/EER Thesis/ERCOT Transition Analysis/misc_stuff/regression_results/",
                            "annual_west_quantreg_", i, ".csv", sep = ""))
}
```

Monthly Summaries

```{r}
for (i in names(monthly_north_qrs)) {
    modeli <- monthly_north_qrs[[i]]
    tidy_qr <- tidy(modeli)
    write.csv(tidy_qr, 
              file = paste("~/EER Thesis/ERCOT Transition Analysis/misc_stuff/regression_results/",
                            "monthly_north_quantreg_", i, ".csv", sep = ""))
}

for (i in names(monthly_houston_qrs)) {
    modeli <- monthly_houston_qrs[[i]]
    tidy_qr <- tidy(modeli)
    write.csv(tidy_qr, 
              file = paste("~/EER Thesis/ERCOT Transition Analysis/misc_stuff/regression_results/",
                            "monthly_houston_quantreg_", i, ".csv", sep = ""))
}

for (i in names(monthly_west_qrs)) {
    modeli <- monthly_west_qrs[[i]]
    tidy_qr <- tidy(modeli)
    write.csv(tidy_qr, 
              file = paste("~/EER Thesis/ERCOT Transition Analysis/misc_stuff/regression_results/",
                            "monthly_west_quantreg_", i, ".csv", sep = ""))
}
```

Hourly Summaries

```{r}
for (i in names(hourly_north_qrs)) {
    modeli <- hourly_north_qrs[[i]]
    tidy_qr <- tidy(modeli)
    write.csv(tidy_qr, 
              file = paste("~/EER Thesis/ERCOT Transition Analysis/misc_stuff/regression_results/",
                            "hourly_north_quantreg_", i, ".csv", sep = ""))
}

for (i in names(hourly_houston_qrs)) {
    modeli <- hourly_houston_qrs[[i]]
    tidy_qr <- tidy(modeli)
    write.csv(tidy_qr, 
              file = paste("~/EER Thesis/ERCOT Transition Analysis/misc_stuff/regression_results/",
                            "hourly_houston_quantreg_", i, ".csv", sep = ""))
}

for (i in names(hourly_west_qrs)) {
    modeli <- hourly_west_qrs[[i]]
    tidy_qr <- tidy(modeli)
    write.csv(tidy_qr, 
              file = paste("~/EER Thesis/ERCOT Transition Analysis/misc_stuff/regression_results/",
                            "hourly_west_quantreg_", i, ".csv", sep = ""))
}
```




```{r}

read_plus <- function(flnm) {
    read_csv(flnm) %>% 
        mutate(filename = flnm)
}
```

```{r}

tbl_with_sources <-
    list.files(path = "~/EER Thesis/ERCOT Transition Analysis/misc_stuff/regression_results/",
               pattern = "*.csv", 
               full.names = T) %>% 
    map_df(~read_plus(.))


tbl_with_sources$X1 <- NULL


tbl_with_sources$factorby <- strsplit(
                              strsplit(
                                gsub("^.*results/?",
                                     "",
                                     tbl_with_sources$filename[1]), 
                                split='.', 
                                fixed=TRUE),
                              split="_",
                              fixed = TRUE)[[1]][1]

tbl_with_sources$factorval <- strsplit(
                              strsplit(
                                gsub("^.*results/?",
                                     "",
                                     tbl_with_sources$filename[1]), 
                                split='.', 
                                fixed=TRUE),
                              split="_",
                              fixed = TRUE)[[1]][4]

tbl_with_sources$region <- strsplit(
                              strsplit(
                                gsub("^.*results/?",
                                     "",
                                     tbl_with_sources$filename[1]), 
                                split='.', 
                                fixed=TRUE),
                              split="_",
                              fixed = TRUE)[[1]][2]

tbl_with_sources$filename <- NULL
```

```{r}
write.csv(tbl_with_sources, 
              file = paste("~/EER Thesis/ERCOT Transition Analysis/misc_stuff/regression_result_analysis/quantile_results.csv", sep = ""), row.names = FALSE)
```

