---
title: "variable_selection"
author: "Eli Ramthun"
date: "4/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#---------------#
# Run Parameters 
#---------------#

set.seed(1)

#---------------#
# Libraries
#---------------#

library(MASS)
library(leaps)
```

```{r}
#---------------#
# Load Data
#---------------#

df <- read.csv(file="data/Cleaned Data/cleaned_timeseries_data_zeroes.csv")

df <- subset(df, select=-c(Season,Date, min_spot_price,max_spot_price))
```

```{r}

# Forward stepsise selection
mod.fwd <- regsubsets(mean_spot_price ~ ., data = df, nvmax = 6, method = "forward") #Models with upto 10 predictors
mod.fwd.sum <- summary(mod.fwd) 
#mod.fwd.sum #Notice which variables are selected in 1,2,3....19 variable models respectively and in what order

# Backward stepwise selection
mod.bck <- regsubsets(mean_spot_price ~ ., data = df, nvmax = 6, method = "backward")#Models with upto 8 predictors
mod.bck.sum <- summary(mod.bck) 
#mod.bck.sum #Notice which variables are selected in 19,18,17...1 variable models respectively and in what order

plot(mod.fwd, scale = "bic") #Notice the variables identified in the best model
plot(mod.bck, scale = "bic") #Notice the variables identified in the best model - are they the same as fwd selection?
```


```{r}
fwd_choices <- mod.fwd.sum$which
fwds <- colnames(fwd_choices[,which(fwd_choices[6,]=="TRUE")])[2:7]

bck_choices <- mod.bck.sum$which
bcks <- colnames(bck_choices[,which(bck_choices[6,]=="TRUE")])[2:7]
```

Forward stepwise selection chose `r fwds` as its predictors; backword stepwise selection chose `r bcks` as its predictors.

```{r}
simple_lm <- lm(Coal ~ Gas + Wind + Nuclear + Solar + Gas_Price + , data= df)
summary(simple_lm)
```

```{r}
ggplotRegression <- function (fit) {

require(ggplot2)

ggplot(fit$model, aes_string(x = names(fit$model)[2], y = names(fit$model)[1])) + 
  geom_point() +
  stat_smooth(method = "lm", col = "red") +
  labs(title = paste("Adj R2 = ",signif(summary(fit)$adj.r.squared, 5),
                     "Intercept =",signif(fit$coef[[1]],5 ),
                     " Slope =",signif(fit$coef[[2]], 5),
                     " P =",signif(summary(fit)$coef[2,4], 5)))
}
```


```{r}
fit1 <- lm(Coal ~ Gas + Wind + Nuclear + Solar + Gas_Price + min_spot_price, data = df)
summary(fit1)
ggplotRegression(fit1)
```

